openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API
  contact:
    name: Chris Y
    email: yeungchiu19908162@gmail.com
  license:
    name: Apache 2.0
    url: 'https://wwww.apache.org/license/LICENSE-2.0.html'
servers:
  - url:  'https://BscComLab062023.yeungchiu256.repl.co'
    description:  Development server
tags:
  - name: Users
    description:  API endpoints for user management.
  - name: Articles
    desciption: Access and perform CRUD operations on blog entries.

paths:
  /articles:
    get:
      tags:
        - Articles
      description:
        Get all articles
    post:
      tags:
        - Articles
      description:
        Add a new article
      requestBody:
        description:  All new article data
        required:  true
        content:
          application/json:
            schema:
              $ref:  ./article.json#/definition/article
  /articles/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        requires: true
        description: Numberic id of the article
    get:
      tags:
        - Articles
      description:
        Get article by ID
      responses:
        '200':
          description:  View of an article record
        '404':
          description:  Article was not found in the DB      
    put:
      tags:
        - Articles
      description:
        Update article by ID
      requestBody:
        description:  All new article data
        required:  true
        content:
          application/json:
            schema:
              $ref:  ./article.json#/definition/article
    delete:
      tags:
        - Articles
      description:
        Delete article by ID
        
    